language: node_js
node_js: "node"

before_deploy:
  - npm run build
  - mv site/1984.html site/index.html
  
deploy:
  provider: surge
  on:
    branch: master
  skip_cleanup: true
  domain: 1984.surge.sh
  project: site/
  
